apiVersion: v1
kind: Namespace
metadata:
  name: carts-go-native

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-go-native
  namespace: carts-go-native
spec:
  selector:
    matchLabels:
      app: carts-go-native
  template:
    metadata:
      labels:
        app: carts-go-native
    spec:
      containers:
      - name: carts-go-native
        image: ttl.sh/a0edf78a-9dee-42f5-9c8d-6cf0e18bcf01:24h
        ports:
        - containerPort: 8080
        command: ["/shoppingcart", "-h", "postgres-postgresql.postgres.svc.cluster.local", "-l", "0.0.0.0:8080"]

---

apiVersion: v1
kind: Service
metadata:
  name: carts-go-native
  namespace: carts-go-native
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
  selector:
    app: carts-go-native

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: carts-go-native
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - http:
      paths:
      - backend:
          service:
            name: carts-go-native
            port:
              number: 8080
        path: /go-native/(.*)
        pathType: ImplementationSpecific
