apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: cart-api
spec:
  image: "ttl.sh/39457471-83e2-4155-88c7-d8bbcc7019c5:24h"
  executor: containerd-shim-spin
  replicas: 2
  variables:
    - name: database_host
      value: pgbouncer.postgres.svc.cluster.local
    - name: database_user
      value: myuser
    - name: database_password
      value: "p05tgr3$"
    - name: database_name
      value: products
    - name: database_port
      value: "5432"
