apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: cart-api
spec:
  image: "ttl.sh/f7cef51e-8400-4123-8f57-80448c761958:24h"
  executor: containerd-shim-spin
  replicas: 2
  variables:
    - name: database_host
      value: postgres-postgresql.postgres.svc.cluster.local
    - name: database_user
      value: myuser
    - name: database_password
      value: "p05tgr3$"
    - name: database_name
      value: products
    - name: database_port
      value: "5432"
