spin_manifest_version = 2

[application]
name = "spin-demo"
version = "0.4.0"
authors = ["benjamin.bajorat <benjamin.bajorat@mayflower.de>"]
description = ""

[variables]

database_host = { default = "localhost" }
database_user = { default = "myuser" }
database_password = { default = "p05tgr3$" }
database_name = { default = "products" }
database_port = { default = "5432" }

# --------------order demo

[[trigger.http]]
route = "/checkout"
component = "order-be"

[component.order-be]
source = "order-be/target/wasm32-wasi/release/order_be.wasm"

environment = { DB_URL = "host=postgres-postgresql.postgres user=myuser password=p05tgr3$ dbname=products" }

allowed_outbound_hosts = ["postgres://postgres-postgresql.postgres:5432"]

[component.order-be.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
workdir = "order-be"

# --------------carts-rs

[[trigger.http]]
route = "/carts-rs/..."
component = "carts-rs"

[component.carts-rs]
source = "carts-rs/target/wasm32-wasi/release/carts_rs.wasm"

allowed_outbound_hosts = ["postgres://{{ database_host }}:{{ database_port }}"]

[component.carts-rs.variables]
database_url = "host={{ database_host }} user={{ database_user }} password={{ database_password }} dbname={{ database_name }}"

[component.carts-rs.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "carts-rs"
watch = ["src/**/*.rs", "Cargo.toml"]

# --------------carts-go

[[trigger.http]]
route = "/carts-go/..."
component = "carts-go"

[component.carts-go]
source = "carts-go/main.wasm"

environment = { DB_URL = "host=postgres-postgresql.postgres user=myuser password=p05tgr3$ dbname=products" }

allowed_outbound_hosts = ["postgres://{{ database_host }}:{{ database_port }}"]

[component.carts-go.variables]
database_url = "host={{ database_host }} user={{ database_user }} password={{ database_password }} dbname={{ database_name }}"

[component.carts-go.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm ."
workdir = "carts-go"
watch = ["**/*.go", "go.mod"]

# --------------carts-ts

[[trigger.http]]
route = "/carts-ts/..."
component = "carts-ts"

[component.carts-ts]
source = "carts-ts/target/carts-ts.wasm"

allowed_outbound_hosts = ["postgres://{{ database_host }}:{{ database_port }}"]

[component.carts-ts.variables]
database_url = "host={{ database_host }} user={{ database_user }} password={{ database_password }} dbname={{ database_name }}"

[component.carts-ts.build]
command = "npm install && npm run build"
workdir = "carts-ts"
watch = ["**/*.ts"]
