spin_manifest_version = 2

[application]
name = "spin-demo"
version = "0.4.0"
authors = ["benjamin.bajorat <benjamin.bajorat@mayflower.de>"]
description = ""

# --------------order demo

[[trigger.http]]
route = "/checkout"
component = "order-be"

[component.order-be]
source = "order-be/target/wasm32-wasi/release/order_be.wasm"

environment = { DB_URL = "host=postgres-postgresql.postgres user=myuser password=p05tgr3$ dbname=products" }

allowed_outbound_hosts = ["postgres://postgres-postgresql.postgres:5432"]

[component.order-be.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
workdir = "order-be"

# --------------carts-rs

[[trigger.http]]
route = "/carts-rs/..."
component = "carts-rs"

[component.carts-rs]
source = "carts-rs/target/wasm32-wasi/release/carts.wasm"

environment = { DB_URL = "host=postgres-postgresql.postgres user=myuser password=p05tgr3$ dbname=products" }

allowed_outbound_hosts = ["postgres://postgres-postgresql.postgres:5432"]

[component.carts-rs.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "carts-rs"
watch = ["src/**/*.rs", "Cargo.toml"]

# --------------carts-go

[[trigger.http]]
route = "/carts-go/..."
component = "carts-go"

[component.carts-go]
source = "carts-go/main.wasm"

environment = { DB_URL = "host=postgres-postgresql.postgres user=myuser password=p05tgr3$ dbname=products" }

allowed_outbound_hosts = ["postgres://postgres-postgresql.postgres:5432"]

[component.carts-go.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm ."
workdir = "carts-go"
watch = ["**/*.go", "go.mod"]

# --------------carts-ts

[[trigger.http]]
route = "/carts-ts/..."
component = "carts-ts"

[component.carts-ts]
source = "carts-ts/target/carts-ts.wasm"

environment = { DB_URL = "host=postgres-postgresql.postgres user=myuser password=p05tgr3$ dbname=products" }

allowed_outbound_hosts = ["postgres://postgres-postgresql.postgres:5432"]

[component.carts-ts.build]
command = "npm run build"
workdir = "carts-ts"
watch = ["**/*.ts"]
