---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-changelog-config
  namespace: postgres
data:
  databaseChangeLog.yml: |
    databaseChangeLog:
      - changeSet:
          id: create-products-table
          author: "joriatyBen"
          changes:
            - createTable:
                catalogName: products
                columns:
                  - column:
                      name: id
                      type: int
                      autoIncrement: true
                      constraints:
                        primaryKey: true
                  - column:
                      name: article_number
                      type: int
                      constraints:
                        nullable: false
                  - column:
                      name: name
                      type: varchar(255)
                      constraints:
                        nullable: false
                  - column:
                      name: image_source
                      type: varchar(255)
                      constraints:
                        nullable: true
                  - column:
                      name: quantity
                      type: int
                      constraints:
                        nullable: false
                  - column:
                      name: sellers_price
                      type: int
                      constraints:
                        nullable: false
                schemaName: products
                tableName: product_details
      - changeSet:
          id: insert-products-table
          author: "joriatyBen"
          changes:
            - insert:
                catalogName: products
                columns:
                  - column:
                      name: article_number
                      value: 1
                  - column:
                      name: name
                      value: Apple
                  - column:
                      name: quantity
                      value: 100
                  - column:
                      name: sellers_price
                      value: 10
                schemaName: products
                tableName: product_details
            - insert:
                catalogName: products
                columns:
                  - column:
                      name: article_number
                      value: 2
                  - column:
                      name: name
                      value: Orange
                  - column:
                      name: quantity
                      value: 75
                  - column:
                      name: sellers_price
                      value: 11
                schemaName: products
                tableName: product_details
            - insert:
                catalogName: products
                columns:
                  - column:
                      name: article_number
                      value: 3
                  - column:
                      name: name
                      value: Grapes
                  - column:
                      name: quantity
                      value: 50
                  - column:
                      name: sellers_price
                      value: 12
                schemaName: products
                tableName: product_details
      - changeSet:
          id: create-customers-table
          author: "joriatyBen"
          changes:
            - createTable:
                catalogName: customers
                columns:
                  - column:
                      name: id
                      type: int
                      autoIncrement: true
                      constraints:
                        primaryKey: true
                  - column:
                      name: name
                      type: varchar(255)
                      constraints:
                        nullable: false
                  - column:
                      name: email
                      type: varchar(255)
                      constraints:
                        nullable: false
                  - column:
                      name: phone
                      type: varchar(32)
                      constraints:
                        nullable: false
                  - column:
                      name: address
                      type: varchar(255)
                      constraints:
                        nullable: false
                  - column:
                      name: city
                      type: varchar(32)
                      constraints:
                        nullable: false
                  - column:
                      name: pin
                      type: varchar(255)
                      constraints:
                        nullable: false
                  - column:
                      name: last_ordered
                      type: datetime
                      constraints:
                        nullable: true
                schemaName: products
                tableName: customers
      - changeSet:
          id: addUniqueConstraint-customers
          author: "joriatyBen"
          changes:
            - addUniqueConstraint:
                catalogName: customers
                columnNames: name, email
                constraintName: unique_name_email
                schemaName: products
                tableName: customers
                validate: true
      - changeSet:
          id: create-order-items-table
          author: "joriatyBen"
          changes:
            - createTable:
                catalogName: order_items
                columns:
                  - column:
                      name: id
                      type: int
                      autoIncrement: true
                      constraints:
                        primaryKey: true
                  - column:
                      name: order_id
                      type: int
                      constraints:
                        nullable: false
                  - column:
                      name: product_id
                      type: int
                      constraints:
                        nullable: false
                  - column:
                      name: order_quantity
                      type: int
                      constraints:
                        nullable: false
                  - column:
                      name: timestamp_created
                      type: datetime
                      constraints:
                        nullable: true
                schemaName: products
                tableName: order_items
      - changeSet:
          id: create-order-details-table
          author: "joriatyBen"
          changes:
            - createTable:
                catalogName: order_details
                columns:
                  - column:
                      name: id
                      type: int
                      autoIncrement: true
                      constraints:
                        primaryKey: true
                  - column:
                      name: timestamp_created
                      type: datetime
                      constraints:
                        nullable: true
                  - column:
                      name: total_products
                      type: varchar(255)
                      constraints:
                        nullable: false
                  - column:
                      name: total_price
                      type: int
                      constraints:
                        nullable: false
                  - column:
                      name: customer_id
                      type: int
                      constraints:
                        nullable: false
                  - column:
                      name: order_state
                      type: varchar(32)
                      constraints:
                        nullable: false
                schemaName: products
                tableName: order_details
      - changeSet:
          id: add-foreign-key-to-order-details
          author: "joriatyBen"
          changes:
            - addForeignKeyConstraint:
                baseTableCatalogName: products
                baseTableSchemaName: products
                baseTableName: order_details
                baseColumnNames: customer_id
                constraintName: fk_customers_id
                referencedTableCatalogName: products
                referencedTableSchemaName: products
                referencedTableName: customers
                referencedColumnNames: id
      - changeSet:
          id: add-foreign-key-to-order-items
          author: "joriatyBen"
          changes:
            - addForeignKeyConstraint:
                baseTableCatalogName: products
                baseTableSchemaName: products
                baseTableName: order_items
                baseColumnNames: order_id
                constraintName: fk_order_id
                referencedTableCatalogName: products
                referencedTableSchemaName: products
                referencedTableName: order_details
                referencedColumnNames: id