---
- name: Add Helm for Prometheus repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install Prometheus from Helm chart
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: 62.7.0
    release_namespace: monitoring
    update_repo_cache: true
    values: "{{ lookup('template', 'values.yml.j2') | from_yaml }}"
    state: present
    wait: true
