[package]
name = "carts"
authors = ["Christian Speckner <christian.speckner@mayflower.de>"]
description = "/carts/{customerId}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "3.0.1"
urlpattern = "^0.2.0"

[workspace]
