deployment:
  enabled: true
  kind: DaemonSet

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"

additionalArguments:
  - "--api.insecure=true"
  - "--accesslog=true"
  - "--log=true"
  - "--log.level=INFO"
  - "--log.format=text"
  - "--ping"
  - "--entrypoints.web.forwardedheaders.insecure=true"
  - "--metrics.prometheus=true"
  - "--metrics.prometheus.addEntryPointsLabels=true"
  - "--metrics.prometheus.addServicesLabels=true"
  - "--metrics.prometheus.entryPoint=metrics"

ports:
  traefik:
    port: 9000
    expose: false
    exposedPort: 9000
  web:
    port: 8000
    expose: true
    exposedPort: 80
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
  metrics:
    port: 9100
    expose: false
    exposedPort: 9100

service:
  enabled: true
  single: true
  type: LoadBalancer
  annotations:
      # dont know if that would work
    service.beta.kubernetes.io/azure-load-balancer-resource-group: wasmdemo
    service.beta.kubernetes.io/azure-pip-name: wasmdemoip
    service.beta.kubernetes.io/azure-dns-label-name: wasmk8scartapi
autoscaling:
  enabled: false

persistence:
  enabled: false

podSecurityContext:
  fsGroup: null